creation_rules:
  - path_regex: .*/mateusclira/.*
    azure_keyvault: https://kv-liratech.vault.azure.net/keys/kms-liratech/38a0e6f5ae3c4df29eb41dcb9ce8cb01
    encrypted_regex: "^(data|stringData|global|apiKey|cfToken|privatekey|publickey)$"
