apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}

data:
  {{- range $key, $value := .Values.environment }}
  {{ $key }}: {{ default "" $value }}
  {{- end }}