apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}

data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ default "" $value | b64enc }}
  {{- end }}