external-dns:
  provider: cloudflare
  fullNameOverride: external-dns
  policy: upsert-only
  env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-creds
        key: token
